#let entry-list = (
  (
    key: "ai",
    short: "AI",
    long: "Artificial Intenligence",
    description: "",
  ),
  (
    key: "stdp",
    short: "STDP",
    long: "Spike-Timing-Dependent Plasticity",
    description: "",
  ),
  (
    key: "fcn",
    short: "FCN",
    long: "Fully Connected Network",
    description: "",
  ),
  (
    key: "dl",
    short: "DL",
    long: "Deep Learning",
    description: "",
  ),
  (
    key: "ltd",
    short: "LTD",
    long: "Long-Term Depression",
    description: "",
  ),
  (
    key: "ltp",
    short: "LTP",
    long: "Long-Term Potentiation",
    description: "",
  ),
  (
    key: "ann",
    short: "ANN",
    long: "Artificial Neural Network",
    description: "",
  ),
  (
    key: "lif",
    short: "LIF",
    long: "Leaky Integrate and Fire",
    description: "",
  ),
  (
    key: "glif",
    short: "GLIF",
    long: "Generalized Leaky Integrate and Fire",
    description: "",
  ),
  (
    key: "ttfs",
    short: "TTFS",
    long: "Time-To-First-Spike",
    description: "",
  ),
  (
    key: "psc",
    short: "PSC",
    long: "Post Synaptic Current",
    description: "",
  ),
  (
    key: "wta",
    short: "WTA",
    long: "Winner-Take-All",
    description: "",
  ),
  (
    key: "dag",
    short: "DAG",
    long: "Directional Acyclic Graph",
    description: "",
  ),
  (
    key: "if",
    short: "IF",
    long: "Integrate and Fire",
    description: "",
  ),
  (
    key: "snn",
    short: "SNN",
    long: "Spiking Neural Network",
    description: "",
  ),
  (
    key: "mlp",
    short: "MLP",
    long: "Multi Layer Perceptron",
    description: "",
  ),
  (
    key: "llm",
    short: "LLM",
    long: "Large Language Model",
    description: "",
  ),
  (
    key: "gpt",
    short: "GPT",
    long: "Generative Pre-trained Transformer",
    description: "",
  ),
  (
    key: "rnn",
    short: "RNN",
    long: "Recurrent Neural Network",
    description: "",
  ),
  (
    key: "lstm",
    short: "LSTM",
    long: "Long Short-Term Memory",
    description: "",
  ),
  (
    key: "xor",
    short: "XOR",
    long: "eXclusive OR",
    description: "",
  ),
  (
    key: "cnn",
    short: "CNN",
    long: "Convolutional Neural Network",
    description: "",
  ),
  (
    key: "cmos",
    short: "CMOS",
    long: "Complementary Metal-Oxide-Semiconductor",
    description: "",
  ),
  (
    key: "vlsi",
    short: "VLSI",
    long: "Very Large Scale Integration",
    description: "",
  ),
  (
    key: "alu",
    short: "ALU",
    long: "Arithmetic Logic Unit",
    description: "",
  ),
  (
    key: "syops",
    short: "SyOPs",
    long: "Synaptic Operations",
    description: "",
  ),
  (
    key: "actionpotential",
    short: "action potential",
    long: "",
    description: "Voltage potential in the neuron cell membrane that propagates trough the neurons axon and to its synapses",
  ),
  (
    key: "spike",
    short: "spike",
    long: "",
    description: "Alias for an action potential that travels trough the network. We refer to a spike as an action potential abtracted into a single event in time",
  ),
)
